{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/failure"},"hierarchy":{"paths":[["doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser","doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode"]]},"metadata":{"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"kind":"text","text":": "},{"text":"ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV","kind":"typeIdentifier"}],"modules":[{"name":"ArgumentParser"}],"roleHeading":"Type Property","externalID":"s:14ArgumentParser8ExitCodeV7failureACvpZ","title":"failure","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14ArgumentParser8ExitCodeV","kind":"typeIdentifier","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode","text":"ExitCode"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"An exit code that indicates that the command failed."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/argumentparser\/exitcode\/failure"]}],"references":{"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode/failure":{"title":"failure","role":"symbol","url":"\/documentation\/argumentparser\/exitcode\/failure","abstract":[{"type":"text","text":"An exit code that indicates that the command failed."}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"kind":"text","text":": "},{"text":"ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/failure","kind":"symbol"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode":{"title":"ExitCode","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ExitCode","kind":"identifier"}],"identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode","type":"topic","url":"\/documentation\/argumentparser\/exitcode","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExitCode","kind":"identifier"}],"abstract":[{"type":"text","text":"An error type that only includes an exit code."}]},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser":{"title":"ArgumentParser","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser","abstract":[],"role":"collection"}}}